# Track database with features mapped from 0.0 to 1.0

TRACKS = [
    {
        "id": 1,
        "title": "Weightless",
        "artist": "Marconi Union",
        "genre": "Ambient",
        "energy": 0.05,
        "valence": 0.15,
        "danceability": 0.10,
        "tempo": 0.15,
        "description": "Induces deep relaxation, featuring slow synth drones, ambient soundscapes, and no rhythm.",
        "url": "https://open.spotify.com/track/6kkwvJ75V34t2Yjq5GwLIe",
        "cover_url": "https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?w=300&q=80"
    },
    {
        "id": 2,
        "title": "Clair de Lune",
        "artist": "Claude Debussy",
        "genre": "Classical",
        "energy": 0.12,
        "valence": 0.35,
        "danceability": 0.22,
        "tempo": 0.20,
        "description": "A beautiful, impressionistic piano piece that is quiet, reflective, and gently emotional.",
        "url": "https://open.spotify.com/track/5u5aV7MvJ1rO565l5nB5Z8",
        "cover_url": "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=300&q=80"
    },
    {
        "id": 3,
        "title": "Someone Like You",
        "artist": "Adele",
        "genre": "Pop / Soul",
        "energy": 0.30,
        "valence": 0.20,
        "danceability": 0.35,
        "tempo": 0.35,
        "description": "A powerful, melancholic piano ballad about lost love and nostalgia.",
        "url": "https://open.spotify.com/track/4JE6eb6t0o2J6J6rxt9lrQ",
        "cover_url": "https://images.unsplash.com/photo-1487180142328-0c4e37023af5?w=300&q=80"
    },
    {
        "id": 4,
        "title": "Liability",
        "artist": "Lorde",
        "genre": "Indie Pop",
        "energy": 0.20,
        "valence": 0.18,
        "danceability": 0.40,
        "tempo": 0.25,
        "description": "An intimate, melancholy keyboard ballad about feeling like a burden to others.",
        "url": "https://open.spotify.com/track/4K65sn4ISPTc5jNuZ5v2gn",
        "cover_url": "/static/images/pop_cover.jpg"
    },
    {
        "id": 5,
        "title": "Spiegel im Spiegel",
        "artist": "Arvo Pärt",
        "genre": "Classical",
        "energy": 0.03,
        "valence": 0.25,
        "danceability": 0.12,
        "tempo": 0.10,
        "description": "A highly meditative, minimalist violin and piano composition offering a profound sense of stillness.",
        "url": "https://open.spotify.com/track/1Lof8p9TzLqE8gMhCwqS3Q",
        "cover_url": "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=300&q=80"
    },
    {
        "id": 6,
        "title": "Get Lucky",
        "artist": "Daft Punk ft. Pharrell Williams",
        "genre": "Disco / Funk Pop",
        "energy": 0.81,
        "valence": 0.86,
        "danceability": 0.81,
        "tempo": 0.55,
        "description": "Incredibly groovy, upbeat, and joyful, perfect for dancing and lifting your mood.",
        "url": "https://open.spotify.com/track/698ZkO214Z5jZ2uiR3X67Y",
        "cover_url": "/static/images/pop_cover.jpg"
    },
    {
        "id": 7,
        "title": "Don't Stop Me Now",
        "artist": "Queen",
        "genre": "Rock",
        "energy": 0.87,
        "valence": 0.90,
        "danceability": 0.55,
        "tempo": 0.78,
        "description": "An explosive, high-energy anthem of pure exhilaration and unstoppable joy.",
        "url": "https://open.spotify.com/track/5T8Ex1kWg2N3Rdf5dUIQCy",
        "cover_url": "https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?w=300&q=80"
    },
    {
        "id": 8,
        "title": "Smells Like Teen Spirit",
        "artist": "Nirvana",
        "genre": "Grunge Rock",
        "energy": 0.91,
        "valence": 0.52,
        "danceability": 0.50,
        "tempo": 0.56,
        "description": "Aggressive, high-energy grunge anthem ideal for venting angst or frustration.",
        "url": "https://open.spotify.com/track/5ghII323ekjL6vY7nkp2zC",
        "cover_url": "https://images.unsplash.com/photo-1524230507669-5ff97982bb5e?w=300&q=80"
    },
    {
        "id": 9,
        "title": "Master of Puppets",
        "artist": "Metallica",
        "genre": "Thrash Metal",
        "energy": 0.98,
        "valence": 0.35,
        "danceability": 0.40,
        "tempo": 0.90,
        "description": "High-intensity thrash metal with aggressive riffs and thunderous speed. Ultimate catharsis.",
        "url": "https://open.spotify.com/track/543b61ns6gKy6j6585t4Cj",
        "cover_url": "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=300&q=80"
    },
    {
        "id": 10,
        "title": "Chop Suey!",
        "artist": "System of a Down",
        "genre": "Alternative Metal",
        "energy": 0.93,
        "valence": 0.28,
        "danceability": 0.42,
        "tempo": 0.65,
        "description": "A chaotic, high-energy metal track combining intense aggression with operatic, tragic sections.",
        "url": "https://open.spotify.com/track/254bqaOaxWQjR26uV23OIU",
        "cover_url": "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=300&q=80"
    },
    {
        "id": 11,
        "title": "Come Away With Me",
        "artist": "Norah Jones",
        "genre": "Vocal Jazz / Acoustic",
        "energy": 0.16,
        "valence": 0.60,
        "danceability": 0.52,
        "tempo": 0.22,
        "description": "A warm, soothing acoustic track with soft jazz vocals, ideal for relaxation and quiet mornings.",
        "url": "https://open.spotify.com/track/0qZED6454WvY1427qg44rr",
        "cover_url": "https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=300&q=80"
    },
    {
        "id": 12,
        "title": "So What",
        "artist": "Miles Davis",
        "genre": "Modal Jazz",
        "energy": 0.28,
        "valence": 0.65,
        "danceability": 0.58,
        "tempo": 0.35,
        "description": "Relaxed, cool jazz instrumentation that is intellectually engaging yet deeply soothing.",
        "url": "https://open.spotify.com/track/4vwwmc3ft45YstX2Eu6ldP",
        "cover_url": "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=300&q=80"
    },
    {
        "id": 13,
        "title": "Warm Horizon",
        "artist": "Lofi Chill Beats",
        "genre": "Lofi Hip Hop",
        "energy": 0.35,
        "valence": 0.55,
        "danceability": 0.65,
        "tempo": 0.25,
        "description": "A cozy, instrumental lofi beat with soft keyboards and a dusty vinyl groove for studying or chilling.",
        "url": "https://open.spotify.com/search/lofi%20hip%20hop",
        "cover_url": "https://images.unsplash.com/photo-1516280440614-37939bbacd6a?w=300&q=80"
    },
    {
        "id": 14,
        "title": "Shape of You",
        "artist": "Ed Sheeran",
        "genre": "Dance Pop",
        "energy": 0.65,
        "valence": 0.82,
        "danceability": 0.83,
        "tempo": 0.37,
        "description": "A highly infectious dance-pop track with a marimba-driven groove and high-energy positivity.",
        "url": "https://open.spotify.com/track/7qiZRh2v756G97tY47U422",
        "cover_url": "/static/images/pop_cover.jpg"
    },
    {
        "id": 15,
        "title": "Electric Feel",
        "artist": "MGMT",
        "genre": "Indie Pop / Synth-Pop",
        "energy": 0.80,
        "valence": 0.78,
        "danceability": 0.76,
        "tempo": 0.42,
        "description": "An upbeat, groovy synth-pop track with psychedelic vibes and positive energy.",
        "url": "https://open.spotify.com/track/3EXiJg58261gh2pa0Jrr0P",
        "cover_url": "/static/images/pop_cover.jpg"
    },
    {
        "id": 16,
        "title": "Bury a Friend",
        "artist": "Billie Eilish",
        "genre": "Dark Pop / Electronic",
        "energy": 0.38,
        "valence": 0.30,
        "danceability": 0.70,
        "tempo": 0.38,
        "description": "Minimalist, creepy electronic beats with whispered vocals; dark, tense, and introspective.",
        "url": "https://open.spotify.com/track/4SSn5FdNCRsiRCRZsi0tS7",
        "cover_url": "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=300&q=80"
    },
    {
        "id": 17,
        "title": "Fix You",
        "artist": "Coldplay",
        "genre": "Alternative Rock",
        "energy": 0.42,
        "valence": 0.45,
        "danceability": 0.30,
        "tempo": 0.45,
        "description": "Builds from a somber organ ballad into an uplifting, cathartic guitar-driven emotional release.",
        "url": "https://open.spotify.com/track/7LVHVU6t6TEIA21jFeiPMj",
        "cover_url": "https://images.unsplash.com/photo-1485579149621-3123dd979885?w=300&q=80"
    },
    {
        "id": 18,
        "title": "Strobe",
        "artist": "Deadmau5",
        "genre": "Progressive House",
        "energy": 0.73,
        "valence": 0.50,
        "danceability": 0.60,
        "tempo": 0.50,
        "description": "A legendary progressive house track that slowly builds from a serene intro to an euphoric, driving synth climax.",
        "url": "https://open.spotify.com/track/6C2B4mE89k526x3LzD5P8a",
        "cover_url": "/static/images/pop_cover.jpg"
    },
    {
        "id": 19,
        "title": "No One Knows",
        "artist": "Queens of the Stone Age",
        "genre": "Stoner Rock",
        "energy": 0.88,
        "valence": 0.58,
        "danceability": 0.52,
        "tempo": 0.58,
        "description": "Driving rock riffs, punchy drums, and a steady rhythmic energy that feels cool and powerful.",
        "url": "https://open.spotify.com/track/6OqZ54N9oXwZJ0RzFw487k",
        "cover_url": "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=300&q=80"
    },
    {
        "id": 20,
        "title": "Sunrise",
        "artist": "Norah Jones",
        "genre": "Vocal Jazz / Pop",
        "energy": 0.22,
        "valence": 0.70,
        "danceability": 0.60,
        "tempo": 0.28,
        "description": "Light, warm, acoustic piano track. Feels like gentle sunlight on a quiet morning.",
        "url": "https://open.spotify.com/track/75JFxk2277b5xsVevZZ936",
        "cover_url": "https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=300&q=80"
    },
    {
        "id": 21,
        "title": "After Hours",
        "artist": "The Weeknd",
        "genre": "Synthwave / R&B",
        "energy": 0.72,
        "valence": 0.38,
        "danceability": 0.67,
        "tempo": 0.48,
        "description": "Atmospheric, late-night R&B with a pulsing synth beat. Dark and emotionally desperate.",
        "url": "https://open.spotify.com/track/2J4t2ZzRkLpLwJ6tE26L1i",
        "cover_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=300&q=80"
    },
    {
        "id": 22,
        "title": "Gymnopédie No. 1",
        "artist": "Erik Satie",
        "genre": "Classical",
        "energy": 0.05,
        "valence": 0.40,
        "danceability": 0.20,
        "tempo": 0.12,
        "description": "A melancholic yet deeply comforting, spacey, atmospheric solo piano piece.",
        "url": "https://open.spotify.com/track/5NGtGxWK5a4y2oJm5lSXTQ",
        "cover_url": "https://images.unsplash.com/photo-1552422535-c45813c61732?w=300&q=80"
    },
    {
        "id": 23,
        "title": "Bad Guy",
        "artist": "Billie Eilish",
        "genre": "Dark Pop / Synth-Pop",
        "energy": 0.43,
        "valence": 0.56,
        "danceability": 0.85,
        "tempo": 0.50,
        "description": "A cheeky, driving minimal bass track with high danceability and playful, sinister vibes.",
        "url": "https://open.spotify.com/track/21jGcNKet2k202rRzyR6ha",
        "cover_url": "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=300&q=80"
    },
    {
        "id": 24,
        "title": "Good Vibrations",
        "artist": "The Beach Boys",
        "genre": "Psychedelic Pop",
        "energy": 0.65,
        "valence": 0.78,
        "danceability": 0.45,
        "tempo": 0.55,
        "description": "A masterpiece of sunny, changing pop harmonies and uplifting, positive vibes.",
        "url": "https://open.spotify.com/track/5tXg9qbEa7k9n871J5uVf0",
        "cover_url": "/static/images/pop_cover.jpg"
    },
    {
        "id": 25,
        "title": "One More Time",
        "artist": "Daft Punk",
        "genre": "French House / Electronic",
        "energy": 0.90,
        "valence": 0.85,
        "danceability": 0.78,
        "tempo": 0.52,
        "description": "A classic house anthem of celebration, high energy, and pure positive synth chords.",
        "url": "https://open.spotify.com/track/0FUDqD9j6b8d96yXh32Q8n",
        "cover_url": "/static/images/pop_cover.jpg"
    }
]
